#!/bin/csh -f
###
rm -rf epg
rm -rf 1.xml
rm -rf 2.xml
rm -rf 3.xml
rm -rf 4.xml

mkdir epg

set today = `date +%Y%m%d`
echo $today


touch 1.xml
#壹電視新聞
set ch_id = "369218"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$ch_id
echo "$link"

#curl "$link" >> 1.xml

#年代新聞
set ch_id = "369247"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$ch_id
#curl https://epg.pw/api/epg.xml\?lang\=zh-hant\&timezone\=QXNpYS9UYWlwZWk%3D\&date\=20250126\&channel_id\=369247 > 2.xml
#curl "$link" >> 1.xml


# 壹新聞
set tvg_id = "369218"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/1.xml
# 年代新聞
set tvg_id = "369247"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/2.xml
# 東森新聞
set tvg_id = "369248"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/3.xml
# 華視新聞
set tvg_id = "368816"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/4.xml
# 民視新聞
set tvg_id = "370172"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/5.xml
# 三立新聞
set tvg_id = "369243"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/6.xml
# TVBS新聞
set tvg_id = "369244"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/7.xml
# 東森財經新聞台
set tvg_id = "370175"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/8.xml
# 台視新聞
set tvg_id = "369307"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/9.xml
# 中視新聞
set tvg_id = "369324"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/10.xml
# 中天新聞
set tvg_id = "370177"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/11.xml
# 民視
set tvg_id = "370139"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/12.xml
# 台視
set tvg_id = "368558"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/13.xml
# 中視
set tvg_id = "334773"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/14.xml
# 華視
set tvg_id = "335088"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/15.xml
# 東森戲劇
set tvg_id = "369227"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/16.xml
# 八大戲劇
set tvg_id = "369226"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/17.xml
# 緯來戲劇
set tvg_id = "369224"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/18.xml
# ELTA娛樂
set tvg_id = "370149"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/19.xml
# 緯來日本
set tvg_id = "369284"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/20.xml
# 緯來綜合
set tvg_id = "368944"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/21.xml
# 八大第一
set tvg_id = "368943"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/22.xml
# 八大綜合
set tvg_id = "368953"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/23.xml
# 中天綜合
set tvg_id = "369192"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/24.xml
# 中天娛樂
set tvg_id = "369183"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/25.xml
# tvN
set tvg_id = "368893"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/26.xml
# 東森綜合
set tvg_id = "272025"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/27.xml
# 東森超視
set tvg_id = "369189"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/28.xml
# ELTA
set tvg_id = "370222"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/29.xml
# 亞洲旅遊頻道
set tvg_id = "369271"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/30.xml
# HBO HD
set tvg_id = "369313"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/31.xml
# AXN
set tvg_id = "368365"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/32.xml
# CINEMAX
set tvg_id = "334710"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/33.xml
# 好萊塢電影台
set tvg_id = "369269"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/34.xml
# 緯來育樂
set tvg_id = "369289"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/35.xml
# 緯來精采
set tvg_id = "368773"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/36.xml
# 緯來體育
set tvg_id = "369287"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/37.xml
# ELEVEN體育1
set tvg_id = "369288"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/38.xml
# ELEVEN體育2
set tvg_id = "335106"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/39.xml
# 博斯無限
set tvg_id = "369235"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/40.xml
# 博斯無限
set tvg_id = "369229"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/41.xml
# 博斯網球
set tvg_id = "370204"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/42.xml
# 博斯運動
set tvg_id = "370202"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/43.xml
# 博斯運動
set tvg_id = "370205"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/44.xml
# 博斯高球一
set tvg_id = "370200"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/45.xml
# 博斯高球
set tvg_id = "370201"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/46.xml
# 博斯魅力
set tvg_id = "370206"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/47.xml
# 時尚運動X
set tvg_id = "370209"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/48.xml
# 智林體育
set tvg_id = "335009"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/49.xml
# NickJr.
set tvg_id = "334895"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/50.xml
# 東森YOYO
set tvg_id = "271829"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/51.xml
# MOMO親子
set tvg_id = "368942"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/52.xml
# 動物星球
set tvg_id = "368948"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/53.xml
# DAZN 2
set tvg_id = "335106"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/54.xml

# 博斯網球
set tvg_id = "369216"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/55.xml
# 博斯運動1
set tvg_id = "368601"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/56.xml
# 博斯運動2
set tvg_id = "405587"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/57.xml


# 博斯高球一
set tvg_id = "369233"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/58.xml
# 博斯高球2
set tvg_id = "369213"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/59.xml
# 博斯魅力
set tvg_id = "368596"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/60.xml
# HBO
set tvg_id = "335015"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/61.xml

# 緯來電影
set tvg_id = "369262"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/62.xml


## 處理檔頭
#rm -rf head.xml
#head -n 2 ./epg/1.xml > head.xml

## 拼接檔案
#rm -rf content.xml
#rm -rf file.xml
#touch content.xml
#touch file.xml



#sed -n "/channel id/,/tv/p" ./epg/1.xml > a.xml
#sed "s/<\/tv>//" a.xml  > content.xml

#sed -n "/channel id/,/tv/p" ./epg/2.xml > a.xml
#sed "s/<\/tv>//" a.xml  >> content.xml


#cat head.xml content.xml >> file.xml
#echo "<\/tv>" >> file.xml


#rm -rf a.xml



