#!/bin/csh -f
###
rm -rf epg
rm -rf 1.xml
rm -rf 2.xml
rm -rf 3.xml
rm -rf 4.xml

mkdir epg

set today = `date +%Y%m%d`
echo $today


touch 1.xml
#壹電視新聞
set ch_id = "369218"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$ch_id
echo "$link"

#curl "$link" >> 1.xml

#年代新聞
set ch_id = "369247"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$ch_id
#curl https://epg.pw/api/epg.xml\?lang\=zh-hant\&timezone\=QXNpYS9UYWlwZWk%3D\&date\=20250126\&channel_id\=369247 > 2.xml
#curl "$link" >> 1.xml


# 壹新聞
set tvg_id = "369218"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/1.xml
# 年代新聞
set tvg_id = "369247"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/2.xml
# 東森新聞
set tvg_id = "369248"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/3.xml
# 華視新聞
set tvg_id = "368816"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/4.xml
# 民視新聞
set tvg_id = "369239"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/5.xml
# 三立新聞
set tvg_id = "369243"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/6.xml
# TVBS新聞
set tvg_id = "369244"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/7.xml
# 東森財經新聞台
set tvg_id = "370175"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/8.xml
# 台視新聞
set tvg_id = "369307"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/9.xml
# 中視新聞
set tvg_id = "369324"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/10.xml
# 中天新聞
set tvg_id = "370177"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/11.xml
# 民視
set tvg_id = "334874"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/12.xml
# 台視
set tvg_id = "334821"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/13.xml
# 中視
set tvg_id = "334773"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/14.xml
# 華視
set tvg_id = "335088"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/15.xml
# 東森戲劇
set tvg_id = "369227"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/16.xml
# 八大戲劇
set tvg_id = "369226"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/17.xml
# 緯來戲劇
set tvg_id = "369224"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/18.xml
# ELTA娛樂
set tvg_id = "370149"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/19.xml
# 緯來日本
set tvg_id = "369284"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/20.xml
# 緯來綜合
set tvg_id = "368944"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/21.xml
# 八大第一
set tvg_id = "368943"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/22.xml
# 八大綜合
set tvg_id = "368953"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/23.xml
# 中天綜合
set tvg_id = "369192"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/24.xml
# 中天娛樂
set tvg_id = "369183"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/25.xml
# tvN
set tvg_id = "2323"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/26.xml
# 東森綜合
set tvg_id = "272025"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/27.xml
# 東森超視
set tvg_id = "369189"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/28.xml
# ELTA
set tvg_id = "370222"
set link = "https://epg.pw/api/epg.xml?lang=zh-hant&timezone=QXNpYS9UYWlwZWk%3D&date="$today"&channel_id="$tvg_id
curl "$link" > ./epg/29.xml
# 亞洲旅遊頻道
set tvg_id = "369271"
# HBO
set tvg_id = "369313"
# AXN
set tvg_id = "369313"
# CINEMAX
set tvg_id = "334710"
# 好萊塢電影台
set tvg_id = "369269"
# 緯來育樂
set tvg_id = "369289"
# 緯來精采
set tvg_id = "335002"
# 緯來體育
set tvg_id = "369287"
# ELEVEN體育1
set tvg_id = "369288"
# ELEVEN體育2
set tvg_id = ""
# 博斯無限
set tvg_id = "369235"
# 博斯無限
set tvg_id = "369229"
# 博斯網球
set tvg_id = "370204"
# 博斯運動
set tvg_id = "370202"
# 博斯運動
set tvg_id = "370205"
# 博斯高球一
set tvg_id = "370200"
# 博斯高球
set tvg_id = "370201"
# 博斯魅力
set tvg_id = "370206"
# 時尚運動X
set tvg_id = "370209"
# 智林體育
set tvg_id = "335009"
# NickJr.
set tvg_id = "334895"
# 東森YOYO
set tvg_id = "271829"
# MOMO親子
set tvg_id = "368942"
# 動物星球
set tvg_id = "368948"




